@startuml
hide footbox

title HighScore Screen Action Sequences

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60


actor User

box "Views" #LightBlue

participant Game
participant End
participant HighScore
participant Start
end box

box "User Interface Control" #LightBlue

participant Navigation
participant CubeFx
participant BlockFx


end box


box "Back End" #c675c5

participant Settings
participant JoggleCube
participant HighScores
participant Score
participant GameTimer
participant Dictionary
participant Cube
participant Block
end box




@enduml