@startuml
hide footbox

title Start Screen Button Action Sequences

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60


actor User

box "Views" #LightBlue

participant StartController
participant LoadGridController
participant GameController

end box

box "User Interface Control" #LightBlue

participant NavigationController

end box 


box "Back End" #c675c5

participant JoggleCubeController

end box
== User Pressing Start Button ==

User -> StartController : btnStartNewGridClicked()
activate StartController
    StartController -> JoggleCubeController : startRandomGrid()
    activate JoggleCubeController
        JoggleCubeController --> StartController
    deactivate JoggleCubeController
StartController -> NavigationController : show(ScreenType.GAME)
    activate NavigationController
        NavigationController -> GameController: prepView()
        activate GameController
            GameController -> JoggleCubeController : getCubeData()
            activate JoggleCubeController
                JoggleCubeController --> GameController : cube[3][3][3]
            deactivate JoggleCubeController
        deactivate GameController
        NavigationController --> StartController
    deactivate NavigationController
deactivate StartController



== User Pressing Load Grid Button ==

User -> StartController : btnLoadGridClicked()
activate StartController
    StartController -> NavigationController : show(ScreenType.LOAD)
    activate NavigationController
        NavigationController -> LoadGridController : prepView()
        activate LoadGridController
        LoadGridController --> NavigationController
        deactivate LoadGridController
        NavigationController --> StartController
    deactivate NavigationController
deactivate StartController
@enduml