@startuml
hide footbox

title Start Screen Button Action Sequences

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60


actor User

box "Views" #LightBlue

participant Start
participant LoadGrid
participant Game

end box

box "User Interface Control" #LightBlue

participant Navigation

end box

box "Back End" #c675c5

participant JoggleCube
participant Cube
participant Block
participant HighScores

end box
== User Pressing Start Button ==

User -> Start : btnStartNewGridClicked()
activate Start
    Start -> JoggleCube : generateRandomGrid()
    activate JoggleCube
        JoggleCube -> Cube : populateGrid(language)
        activate Cube
            loop foreach 27 blocks in the cube
                Cube -> Block : <<create>>(randomLetter)
                activate Block
                    Block --> Cube
                deactivate Block
            end
            Cube --> JoggleCube
        deactivate Cube
        JoggleCube -> HighScores : <<create>>
        activate HighScores
            HighScores --> JoggleCube
        deactivate HighScores
        JoggleCube --> Start
    deactivate JoggleCube
Start -> Navigation : show(ScreenType.GAME)
    activate Navigation
        Navigation -> Game: prepView()
        activate Game
            Game -> JoggleCube : getCubeData()
            activate JoggleCube
                JoggleCube -> Cube : getCube()
                activate Cube
                    Cube --> JoggleCube : cube[3][3][3]
                deactivate Cube
                JoggleCube --> Game : cube[3][3][3]
            deactivate JoggleCube
            Game --> Navigation
        deactivate Game
        Navigation --> Start
    deactivate Navigation
deactivate Start



== User Pressing Load Grid Button ==

User -> Start : btnLoadGridClicked()
activate Start
    Start -> Navigation : show(ScreenType.LOAD)
    activate Navigation
        Navigation -> LoadGrid : prepView()
        activate LoadGrid
            LoadGrid -> JoggleCube : getRecentGrids()
            activate JoggleCube
                JoggleCube --> LoadGrid : listOfFiles
            deactivate JoggleCube
            LoadGrid --> Navigation
        deactivate LoadGrid
        Navigation --> Start
    deactivate Navigation
deactivate Start
@enduml