@startuml
hide footbox

title Program Launch Action Sequence

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60


actor User

participant Main

box "User Interface Control" #LightBlue

participant UI
participant Navigation

end box


box "Back End" #c675c5

participant JoggleCube
participant HighScores
participant Score
participant Dictionary

end box



User -> Main : main()
Main -> Main : start()
activate Main

== launch the backend ==
Main -> JoggleCube : getInstance()
JoggleCube -> JoggleCube : <<create>>
activate JoggleCube

JoggleCube -> HighScores : loadScores(file)
activate HighScores

loop as many times as needed
    HighScores -> Score : loadScore()
    activate Score
    Score --> HighScores
    deactivate Score
end

HighScores --> JoggleCube
deactivate HighScores

JoggleCube -> Dictionary : <<create>>
activate Dictionary

Dictionary --> JoggleCube
deactivate Dictionary

JoggleCube -> Dictionary : loadDictionary(language)
activate Dictionary

Dictionary --> JoggleCube
deactivate Dictionary

JoggleCube --> Main
deactivate JoggleCube

== Launch the front end ==

Main -> UI : getInstance()

UI -> UI : <<create>>
activate UI


UI --> Main
deactivate UI
Main -> UI : initialize()
activate UI
UI -> Navigation : getInstance()

Navigation -> Navigation : <<create>>
activate Navigation
Navigation --> UI
deactivate Navigation

UI -> Navigation : setMainScene(main)
activate Navigation
Navigation --> UI
deactivate Navigation

loop foreach ScreenType
    UI -> UI : createScreen(ScreenType)
    UI -> Navigation : add(ScreenType,Screen)
    activate Navigation
    Navigation --> UI
    deactivate Navigation
end

UI -> Navigation : switchScreen(ScreenType.Start)
activate Navigation
Navigation --> UI
deactivate Navigation
UI --> Main
deactivate UI
deactivate Main

@enduml