@startuml Obect Diagram

object main
object ui
object navigation

object joggleCube {
    dictionary=["a","aa","ab",....,"Zoo"]
}

object cube {
    cube=[block,block,block]
            [block,block,block]
            [bock,block,block]
    letterBag=["A","B",...."Qu",....,"Z"]
    
}

object block {
    letter="I"
}

object gridScores {
    scores=[score,score,....]
}

object overallScores {
    scores=[score,score....]
}

object score1 {
    name="Tom"
    score= 100
    date="03/03/18 15:00"
}
object score2 {
    name="Tom"
    score= 100
    date="03/03/18 15:00"
}

joggleCube --> "1" gridScores
joggleCube --> "1" overallScores
joggleCube --> "1" cube

gridScores --> "∞" score1
overallScores --> "∞" score2

cube --> "27" block

main --> "1" joggleCube
main --> "1" ui
ui --> "1" navigation
@enduml