@startuml
hide footbox

title Start Screen Button Action Sequences

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60


actor User

box "Views" #LightBlue

participant StartController
participant LoadGridController
participant GameController

end box

box "User Interface Control" #LightBlue

participant UIController
participant ScreenController

end box 


box "Back End" #c675c5

participant JoggleCube 

end box
== User Pressing Start Button ==

User -> StartController : btnStartNewGridClicked()
activate StartController

StartController -> UIController : getScreenController.show(ScreenType.GAME)
activate UIController
UIController -> ScreenController : show(ScreenType.GAME)
deactivate UIController

StartController -> UIController : getJoggleCube.startRandomGrid()
activate UIController
UIController -> JoggleCube : startRandomGrid()
activate JoggleCube
deactivate JoggleCube
deactivate UIController

StartController -> UIController : initializeController(ScreenType.GAME)
activate UIController

UIController -> GameController : initialize()
activate GameController

GameController -> UIController : getJoggleCube().getCubeData()
activate UIController #ff0000

UIController -> JoggleCube : getCubeData()
activate JoggleCube
JoggleCube --> UIController : cube[3][3][3]
deactivate JoggleCube

UIController --> GameController : cube[3][3][3]
deactivate UIController #ff0000
deactivate GameController

deactivate UIController
deactivate StartController



== User Pressing Load Grid Button ==

User -> StartController : btnLoadGridClicked()
activate StartController

StartController -> UIController : getScreenController.show(ScreenType.LOAD)
activate UIController
UIController -> ScreenController : show(ScreenType.LOAD)
deactivate UIController

StartController -> UIController : initializeController(ScreenType.LOAD)
activate UIController

UIController -> LoadGridController : initialize()
activate LoadGridController

LoadGridController -> UIController : getJoggleCube().getRecentGrids()
activate UIController #ff0000
UIController -> JoggleCube : getRecentGrids()
activate JoggleCube
JoggleCube --> UIController : ListOfRecents
deactivate JoggleCube
UIController --> LoadGridController : ListOfRecents
deactivate UIController #ff0000

deactivate LoadGridController
deactivate UIController

deactivate StartController
@enduml